name: Build android-wuwa framework

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  matrix-builder:
    # 引用上述分离出的底层车间模版
    uses: ./.github/workflows/ddk-lkm.yml
    strategy:
      # 阻断连锁失败：某一个碎片化内核编译失败，不影响其他成功版本的产物输出
      fail-fast: false
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
    with:
      kmi: ${{ matrix.kmi }}
      ddk_release: '20251016'
      module_name: 'android-wuwa'
