name: Build android-wuwa framework

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  matrix-builder:
    uses: ./.github/workflows/ddk-lkm.yml
    strategy:
      fail-fast: false
      matrix:
        kmi:
          - android11-5.4
          - android12-5.4
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
    with:
      kmi: ${{ matrix.kmi }}
      ddk_release: '20251016'
      module_name: 'android-wuwa'
